---
services:
  livekit:
    image: livekit/livekit-server:latest

    command: --config /out/config.yaml --dev

    platform: linux/amd64

    networks:
      - default

    ports:
      - 0.0.0.0:7880:7880
      - 0.0.0.0:7881:7881

    volumes:
      - ./livekit-server:/out

  egress:
    image: livekit/egress:v1.9

    cap_add:
      - SYS_ADMIN

    environment:
      EGRESS_CONFIG_FILE: /out/config.yaml

    networks:
      - default

    platform: linux/amd64

    volumes:
      - ./livekit-egress:/out

  redis:
    image: redis:6

    networks:
      - default

    platform: linux/amd64

    ports:
      - 0.0.0.0:6380:6379

networks:
  default:
